# Generated by Django 2.2.16 on 2020-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201013_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Wanted', 'Wanted'), ('Missing', 'Missing')], max_length=30),
        ),
    ]
