# Generated by Django 2.2.17 on 2020-12-13 09:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Wanted', 'Wanted'), ('Missing', 'Missing'), ('Found', 'Found')], max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/thereaper/PycharmProjects/python_FaceRecognition/media/files'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='spottedcitizen',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Wanted', 'Wanted'), ('Missing', 'Missing'), ('Found', 'Found')], max_length=30),
        ),
    ]
