# Generated by Django 2.2.18 on 2021-04-07 11:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20201213_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/reaper/Projects/python_FaceRecognition/media/files'), upload_to=''),
        ),
    ]
