# Generated by Django 2.2.18 on 2021-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20210407_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spottedcitizen',
            old_name='bio',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='spottedcitizen',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='spottedcitizen',
            name='citizen_image',
        ),
        migrations.RemoveField(
            model_name='spottedcitizen',
            name='citizenship_number',
        ),
        migrations.RemoveField(
            model_name='spottedcitizen',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='spottedcitizen',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spottedcitizen',
            name='image',
            field=models.ImageField(default=1, upload_to='spotted/'),
            preserve_default=False,
        ),
    ]
