# Generated by Django 2.2.20 on 2021-04-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20210417_2042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
