# Generated by Django 2.2.20 on 2021-04-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='citizenship_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='spottedcitizen',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
