# Generated by Django 2.2.20 on 2021-04-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_auto_20210429_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='spottedcitizen',
            name='date_of_spotted',
            field=models.DateTimeField(null=True),
        ),
    ]
