# Generated by Django 2.2.16 on 2020-10-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(max_length=100)),
                ('date_of_case', models.DateTimeField(blank=True, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='cases/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('Wanted', 'Wanted'), ('Spotted', 'Spotted'), ('Missing', 'Missing'), ('Found', 'Found')], max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
