# Generated by Django 2.2.20 on 2021-04-26 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('case_first_name', models.CharField(max_length=50, null=True)),
                ('case_last_name', models.CharField(max_length=50, null=True)),
                ('case_location', models.CharField(max_length=50, null=True)),
                ('date_of_case', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='cases/')),
                ('status', models.CharField(choices=[('Wanted', 'Wanted'), ('Spotted', 'Spotted'), ('Missing', 'Missing'), ('Found', 'Found')], max_length=10)),
                ('case_description', models.TextField(blank=True, max_length=500, null=True)),
                ('reporter_first_name', models.CharField(max_length=50, null=True)),
                ('reporter_last_name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=14, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('reporter_description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
