# Generated by Django 2.2.16 on 2020-10-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesmodel',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Wanted', 'Wanted'), ('Spotted', 'Spotted'), ('Missing', 'Missing'), ('Found', 'Found')], max_length=10, null=True),
        ),
    ]
