# Generated by Django 2.2.20 on 2021-04-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesmodel',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='reporter_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='reporter_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
