# Generated by Django 2.2.18 on 2021-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_casesmodel_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesmodel',
            name='nationality',
            field=models.CharField(default='', max_length=50),
        ),
    ]
