# Generated by Django 2.2.18 on 2021-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20210417_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesmodel',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
