# Generated by Django 2.2.18 on 2021-04-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20210417_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesmodel',
            name='nationality',
            field=models.CharField(default='Nepali', max_length=50, null=True),
        ),
    ]
