# Generated by Django 2.2.20 on 2021-04-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20210417_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesmodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
