# Generated by Django 2.2.20 on 2021-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_casesmodel_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesmodel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
