# Generated by Django 2.2.20 on 2021-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20210423_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesmodel',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='contact_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='status',
            field=models.CharField(choices=[('Wanted', 'Wanted'), ('Spotted', 'Spotted'), ('Missing', 'Missing'), ('Found', 'Found')], max_length=10, null=True),
        ),
    ]
