# Generated by Django 2.2.20 on 2021-04-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20210423_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesmodel',
            name='date_of_case',
            field=models.DateTimeField(null=True),
        ),
    ]
