# Generated by Django 2.2.20 on 2021-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='case',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='case',
            field=models.ManyToManyField(null=True, to='cases.CasesModel'),
        ),
    ]
