# Generated by Django 2.2.20 on 2021-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20210428_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='case',
            field=models.ManyToManyField(to='cases.CasesModel'),
        ),
    ]
