# Generated by Django 2.2.20 on 2021-04-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210428_2311'),
        ('feedback', '0005_remove_feedbackmodel_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.CasesModel'),
        ),
    ]
