# Generated by Django 2.2.20 on 2021-04-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedbackmodel_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='last_name',
        ),
    ]
