# Generated by Django 2.2.17 on 2020-12-16 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='media/citizens')),
                ('nationality', models.CharField(max_length=50)),
                ('citizenship_number', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=500)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Wanted', 'Wanted'), ('Missing', 'Missing'), ('Found', 'Found')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
